FROM golang:alpine

WORKDIR /var/lib/benchmark

ENV PYTHONUNBUFFERED=1

RUN apk update

RUN apk add make automake gcc g++ curl python3 python3-dev py3-numpy hdf5-dev && ln -sf python3 /usr/bin/python

RUN ln -s /usr/include/locale.h /usr/include/xlocale.h

RUN python3 -m ensurepip

RUN pip3 install --no-cache --upgrade pip setuptools

COPY benchmark-scripts/src/requirements.txt /var/lib/benchmark/requirements.txt

RUN pip3 install -r requirements.txt

COPY ./benchmarker ./

RUN go build -o benchmarker .

CMD [ "python", "./benchmark.py" ]

# copy benchmarking scripts last, so that when paramters are changed, the rest
# can be taken from cache
COPY benchmark-scripts/ann/benchmark.py /var/lib/benchmark/benchmark.py

COPY benchmark-scripts/src/functions.py /var/lib/benchmark/functions.py
